name: unicef
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  animate_do: ^4.2.0
  image_picker: ^1.2.1
  awesome_dialog: ^3.3.0
  provider: ^6.1.5+1
  flutter_keyboard_visibility: ^6.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

# ---------------------------
# APP ICON CONFIGURATION
# ---------------------------
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.jpeg"

# ---------------------------
# SPLASH SCREEN CONFIGURATION
# ---------------------------
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash.jpg"
  android: true
  ios: true
  android_gravity: center
  web: true
  
  android_12:
    image: "assets/splash.jpg"
    icon_background_color: "#FFFFFF"
  


flutter:
  uses-material-design: true

  assets:
    - assets/imgicon1.png
    - assets/modi.jpg
    - assets/logo.jpeg
    - assets/splash.jpg
